#!/usr/bin/env python3
"""Audit the 751 legacy monomer PDB headers without running any model.

Example:
  python scripts/audit_monomer_pdb_provenance.py \
    --legacy-repo /path/to/DCarchimonde-ProteinMPNN \
    --output data/Monomer_PDB_Provenance_751.csv
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import re
from collections import Counter
from pathlib import Path


SOURCE_REPO = "DCarchimonde/ProteinMPNN"
SOURCE_COMMIT = "28dff152d83623dfb322480413b7dc889f8537a4"
EXPECTED_VERSIONS = {
    "2023.35+release.23439d3": 406,
    "2025.25+release.a0cefad01b": 345,
}


def read_names(path: Path) -> set[str]:
    names = set()
    with path.open(encoding="utf-8") as handle:
        for line in handle:
            record = json.loads(line)
            assert record["name"] not in names
            names.add(record["name"])
    return names


def read_sequences(path: Path) -> dict[str, str]:
    records = {}
    with path.open(encoding="utf-8") as handle:
        for line in handle:
            record = json.loads(line)
            assert record["name"] not in records
            assert record["seq"] == record["seq_chain_A"]
            records[record["name"]] = record["seq"]
    return records


def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def git_blob_sha1(data: bytes) -> str:
    prefix = f"blob {len(data)}\0".encode()
    return hashlib.sha1(prefix + data).hexdigest()


def audit(legacy_repo: Path, output: Path, overlap_output: Path | None) -> None:
    data_root = legacy_repo / "nmethyl_data"
    pdb_dir = data_root / "raw_pdb"
    all_names = read_names(data_root / "processed" / "all_data.jsonl")
    train_names = read_names(data_root / "training_set" / "train.jsonl")
    test_names = read_names(data_root / "test_set" / "test.jsonl")
    assert len(all_names) == 751
    assert len(train_names) == 600
    assert len(test_names) == 151
    assert train_names.isdisjoint(test_names)
    assert train_names | test_names == all_names

    train_sequences = read_sequences(data_root / "training_set" / "train.jsonl")
    test_sequences = read_sequences(data_root / "test_set" / "test.jsonl")
    assert set(train_sequences) == train_names
    assert set(test_sequences) == test_names

    rows = []
    version_counts: Counter[str] = Counter()
    panel_split_counts: Counter[tuple[str, str]] = Counter()
    for pdb_path in sorted(pdb_dir.glob("*.pdb"), key=lambda path: path.name):
        data = pdb_path.read_bytes()
        text = data.decode("ascii", errors="replace")
        lines = text.splitlines()
        sample_name = pdb_path.stem
        assert sample_name in all_names
        split = "train" if sample_name in train_names else "test"
        prefix = "Me_" if sample_name.startswith("Me_") else "pdb_"
        assert sample_name.startswith(prefix)

        expdta_lines = [line.strip() for line in lines if line.startswith("EXPDTA")]
        assert len(expdta_lines) == 1
        expdta = re.sub(r"^EXPDTA\s+", "", expdta_lines[0])
        assert expdta == "THEORETICAL MODEL"
        rosetta_marker = any("MODEL GENERATED BY ROSETTA" in line for line in lines)
        assert rosetta_marker

        versions = [
            match.group(1)
            for line in lines
            if (match := re.search(r"^REMARK 220\s+VERSION\s+(\S+)", line))
        ]
        assert len(versions) == 1
        version = versions[0]
        if prefix == "Me_":
            assert version == "2023.35+release.23439d3"
            panel = "Rosetta-2023"
        else:
            assert version == "2025.25+release.a0cefad01b"
            panel = "Rosetta-2025"

        header_line = next((line for line in lines if line.startswith("HEADER")), "")
        date_match = re.search(r"(\d{2}-[A-Z]{3}-\d{2})", header_line)
        header_date = date_match.group(1) if date_match else ""
        version_counts[version] += 1
        panel_split_counts[(panel, split)] += 1
        rows.append(
            {
                "sample_name": sample_name,
                "split": split,
                "prefix": prefix,
                "source_panel": panel,
                "pdb_relpath": f"nmethyl_data/raw_pdb/{pdb_path.name}",
                "expdta": expdta,
                "rosetta_marker": 1,
                "rosetta_version": version,
                "header_date": header_date,
                "file_size_bytes": len(data),
                "file_sha256": sha256(data),
                "git_blob_sha1": git_blob_sha1(data),
                "source_repo": SOURCE_REPO,
                "source_commit": SOURCE_COMMIT,
            }
        )

    assert len(rows) == 751
    assert {row["sample_name"] for row in rows} == all_names
    assert dict(version_counts) == EXPECTED_VERSIONS
    assert panel_split_counts == Counter(
        {
            ("Rosetta-2023", "train"): 323,
            ("Rosetta-2025", "train"): 277,
            ("Rosetta-2023", "test"): 83,
            ("Rosetta-2025", "test"): 68,
        }
    )

    output.parent.mkdir(parents=True, exist_ok=True)
    with output.open("w", newline="", encoding="utf-8-sig") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0]))
        writer.writeheader()
        writer.writerows(rows)
    print(f"Wrote {len(rows)} audited PDB records to {output}")

    if overlap_output is not None:
        train_naturalized = {sequence.upper() for sequence in train_sequences.values()}
        test_naturalized = {sequence.upper() for sequence in test_sequences.values()}
        overlap_report = {
            "source_repo": SOURCE_REPO,
            "source_commit": SOURCE_COMMIT,
            "train_records": len(train_sequences),
            "test_records": len(test_sequences),
            "exact_name_overlap_count": len(train_names & test_names),
            "exact_name_overlap": sorted(train_names & test_names),
            "train_unique_naturalized_sequences": len(train_naturalized),
            "test_unique_naturalized_sequences": len(test_naturalized),
            "exact_naturalized_sequence_overlap_count": len(train_naturalized & test_naturalized),
            "exact_naturalized_sequence_overlap": sorted(train_naturalized & test_naturalized),
            "scope_limit": "Exact name and exact naturalized-sequence audit only; no homology clustering was performed.",
        }
        assert overlap_report["exact_name_overlap_count"] == 0
        assert overlap_report["exact_naturalized_sequence_overlap_count"] == 0
        overlap_output.parent.mkdir(parents=True, exist_ok=True)
        overlap_output.write_text(
            json.dumps(overlap_report, ensure_ascii=False, indent=2) + "\n",
            encoding="utf-8",
        )
        print(f"Wrote exact-overlap audit to {overlap_output}")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--legacy-repo", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--overlap-output", type=Path)
    args = parser.parse_args()
    audit(
        args.legacy_repo.resolve(),
        args.output.resolve(),
        args.overlap_output.resolve() if args.overlap_output else None,
    )


if __name__ == "__main__":
    main()
